[[redirects]]
  from = "/api"
  to = "https://staging-ituyen.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/*
  to = ":splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}