[[redirects]]
  from = "/api"
  to = "https://staging-ituyen.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/product/create"
  to = "https://staging-ituyen.herokuapp.com/product/create"
  force = true
  headers = {X-From = "Netlify"}