[[redirects]]
  from = "/api"
  to = "https://staging-ituyen.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/*"
  to = "https://staging-ituyen.herokuapp.com/*"
  force = true
  headers = {X-From = "Netlify"}